spring.application.name=tp8-monitoring
server.port=8081

management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.info.env.enabled=true

management.prometheus.metrics.export.enabled=true

info.app.name=Spring Monitoring App
info.app.version=1.0.0
info.app.description=TP8 Monitoring Logging Spring Boot

logging.level.root=INFO
logging.level.ma.fst.tp8monitoring=DEBUG
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n